import { handleGeneralCommands } from '../commands/general';
import { handleAICommands } from '../commands/ai';
import { handleUserCommands } from '../commands/user';
import { handleAdminCommands } from '../commands/admin';
import { handleFunCommands } from '../commands/fun';
import { handleSocialCommands } from '../commands/social';
import { handleMediaCommands } from '../commands/media';
import { PermissionGuard } from './Guards';

export const COMMAND_MAP: Record<string, Function> = {
  // GERAL
  'menu': handleGeneralCommands,
  'vencimento': handleGeneralCommands,
  'ajuda': handleGeneralCommands,
  'filhote.ajuda': handleGeneralCommands,

  // IA
  'filhote': handleAICommands,
  'resumir': handleAICommands,
  'resume': handleAICommands,
  'resumo': handleAICommands,

  // PESSOAL
  'meusdados': handleUserCommands,
  'dados': handleUserCommands,
  'perfil': handleUserCommands,
  'bio': handleUserCommands,
  'niver': handleUserCommands,
  'niver.excluir': handleUserCommands,
  'nivers': handleUserCommands,
  'signos': handleUserCommands,
  'meuig': handleUserCommands,
  'meuig.excluir': handleUserCommands,
  'local': handleUserCommands,
  'local.excluir': handleUserCommands,
  'radio': handleSocialCommands,
  'radio.excluir': handleUserCommands,
  'playlist': handleSocialCommands,
  'ignoreme': handleUserCommands,
  'meignore': handleUserCommands,

  // SOCIAL
  'role.criar': handleSocialCommands,
  'resenha.criar': handleSocialCommands,
  'role.encerrar': handleSocialCommands,
  'role.cancelar': handleSocialCommands,
  'resenha.cancelar': handleSocialCommands,
  'resenha.fim': handleSocialCommands,
  'roles': handleSocialCommands,
  'role.vou': handleSocialCommands,
  'vou': handleSocialCommands,
  'role.nvou': handleSocialCommands,
  'vounao': handleSocialCommands,
  'nvou': handleSocialCommands,
  'role.sair': handleSocialCommands,
  'iglist': handleUserCommands,
  'locallist': handleUserCommands,
  'resenha': handleSocialCommands,

  // ALIASES DE NICHO / LISTA (TODOS OS 10 SOLICITADOS)
  'lista.entrar': handleSocialCommands,
  'nicho.entrar': handleSocialCommands,
  'lista.sim': handleSocialCommands,
  'nicho.sim': handleSocialCommands,
  'lista.participar': handleSocialCommands,
  'nicho.participar': handleSocialCommands,
  'lista.quero': handleSocialCommands,
  'nicho.quero': handleSocialCommands,
  'lista.todentro': handleSocialCommands,
  'nicho.todentro': handleSocialCommands,

  // ALIASES DE SAIR DE NICHO
  'lista.sair': handleSocialCommands,
  'nicho.sair': handleSocialCommands,
  'lista.nao': handleSocialCommands,
  'nicho.nao': handleSocialCommands,
  'lista.nparticipar': handleSocialCommands,
  'nicho.nparticipar': handleSocialCommands,
  'lista.nquero': handleSocialCommands,
  'nicho.nquero': handleSocialCommands,
  'lista.tofora': handleSocialCommands,
  'nicho.tofora': handleSocialCommands,

  // ENTRETENIMENTO
  'chance': handleFunCommands,
  'sortear': handleFunCommands,
  'sorteio': handleFunCommands,
  'viadometro': handleFunCommands,
  'gadometro': handleFunCommands,
  'bafometro': handleFunCommands,
  'detector': handleFunCommands,
  'casal': handleFunCommands,
  'dado': handleFunCommands,
  'moeda': handleFunCommands,
  'd4': handleFunCommands,
  'd6': handleFunCommands,
  'd8': handleFunCommands,
  'd10': handleFunCommands,
  'd12': handleFunCommands,
  'd20': handleFunCommands,
  'versiculo': handleFunCommands,
  'biblia': handleFunCommands,
  'jesus': handleFunCommands,
  'sortedodia': handleFunCommands,
  'sdd': handleFunCommands,
  'amg.lembrar': handleFunCommands,

  // MEDIA
  'musica': handleMediaCommands,
  'tocar': handleMediaCommands,
  'ig': handleMediaCommands,
  'igdl': handleMediaCommands,
  'instadl': handleMediaCommands,
  'fb': handleMediaCommands,
  'fbdl': handleMediaCommands,
  'tiktok': handleMediaCommands,
  'tkdl': handleMediaCommands,
  'yt': handleMediaCommands,
  'ytdl': handleMediaCommands,
  'fig': handleMediaCommands,
  'brat': handleMediaCommands,
  'bratv': handleMediaCommands,
  'emojimix': handleMediaCommands,
  'mix': handleMediaCommands,
  'qc': handleMediaCommands,
  'quote': handleMediaCommands,
  'transcrever': handleMediaCommands,
  'ouvir': handleMediaCommands,

  // ADMIN
  'admins': handleAdminCommands,
  'adms': handleAdminCommands,
  'remover': handleAdminCommands,
  'ban': handleAdminCommands,
  'banir': handleAdminCommands,
  'desban': handleAdminCommands,
  'desbanir': handleAdminCommands,
  'adv': handleAdminCommands,
  'promover': handleAdminCommands,
  'rebaixar': handleAdminCommands,
  'demitir': handleAdminCommands,
  'apagar': handleAdminCommands,
  'limpar': handleAdminCommands,
  'marcar': handleAdminCommands,
  'alertar': handleAdminCommands,
  'avisar': handleAdminCommands,
  'abrir': handleAdminCommands,
  'fechar': handleAdminCommands,
  'modoadmin': handleAdminCommands,
  'zerar': handleAdminCommands,
  'zerar.logs': handleAdminCommands,
  'limpar.logs': handleAdminCommands,

  // TESTES
  'debug': handleGeneralCommands,
  'teste': handleGeneralCommands,
  'bomdia': handleGeneralCommands,
  'boatarde': handleGeneralCommands,
  'boanoite': handleGeneralCommands,
  'oi': handleGeneralCommands,

  // ESTATÍSTICAS
  'mensagens': handleAdminCommands,
  'ativos': handleAdminCommands,
  'desocupados': handleAdminCommands,
  'inativos': handleAdminCommands,
  'passivos': handleAdminCommands,
};
